# Generated by Django 5.1.1 on 2024-09-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('se_da_bem', models.TextField()),
                ('nao_se_da_bem', models.TextField()),
                ('indiferente', models.TextField()),
            ],
        ),
    ]
