# Generated by Django 5.1.1 on 2024-09-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='texto_gerado',
            field=models.TextField(blank=True, help_text='Texto gerado pela IA para esta planta.', null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='indiferente',
            field=models.TextField(help_text='Plantas indiferentes a esta planta.'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nao_se_da_bem',
            field=models.TextField(help_text='Plantas que não se dão bem com esta planta.'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='se_da_bem',
            field=models.TextField(help_text='Plantas que se dão bem com esta planta.'),
        ),
    ]
