# Generated by Django 5.1.1 on 2024-09-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_cc', '0013_remove_clube_categoria_remove_clube_modalidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('se_da_bem', models.TextField()),
                ('nao_se_da_bem', models.TextField()),
                ('indiferente', models.TextField()),
            ],
        ),
    ]
